from __future__ import annotations

WILL_ASK_QUESTIONS = 'I_NEED_TO_ASK_SOME_QUESTIONS_BEFORE_I_PROCEED'
HERE_IS_MY_STEP_BY_STEP_PLAN = 'HERE_IS_MY_STEP_BY_STEP_PLAN'
WILL_ANSWER_DIRECTLY = 'I_WILL_ANSWER_THIS_STEP_DIRECTLY'
UNSOLVABLE = 'UNSOLVABLE_I_GIVE_UP'
MY_ANSWER = 'MY_ANSWER'
MY_FINAL_ANSWER = "MY_FINAL_ANSWER"
MY_QUESTIONS = 'MY_QUESTIONS'
NEXT_I_WANT_TO_WORK_AT = "NEXT_I_WANT_TO_WORK_AT"

ROLE_SYSTEM = 'system'
ROLE_SOLVER = 'Tao'
ROLE_SAGE = 'Sage'
ROLE_ORCHESTRATOR = 'orchestrator'
ROLE_USER = 'user'

USER_ANSWERS = 'USER_ANSWERS'

TRUE_OR_FALSE = 'true or false'

MAX_RETRIES = 5
MAX_BRANCHING_FACTOR = 1
MAX_VOTING_FACTOR = 1
CONTINUE_VOTE_QUORUM = 0.6
DONE = 'DONE'
CONTINUE = 'CONTINUE'
FREE_TEXT = '_FREE'
