from __future__ import annotations

WILL_ASK_QUESTIONS = 'I_NEED_TO_ASK_SOME_QUESTIONS_BEFORE_I_PROCEED'
HERE_IS_MY_STEP_BY_STEP_PLAN = 'HERE_IS_MY_STEP_BY_STEP_PLAN'
WILL_ANSWER_DIRECTLY = 'I_WILL_ANSWER_DIRECTLY'
WILL_ASK_GENIE = 'LET_ME_ASK_THE_PYTHON_GENIE'
UNSOLVABLE = 'UNSOLVABLE_I_GIVE_UP'
MY_ANSWER = 'MY_ANSWER'
NEXT_I_WANT_TO_WORK_AT = "NEXT_I_WANT_TO_WORK_AT"
FINAL_ANSWER = 'FINAL_ANSWER'

ROLE_SYSTEM = 'system'
ROLE_TAO = 'Tao'
ROLE_SAGE = 'Sage'
ROLE_ORCHESTRATOR = 'orchestrator'
ROLE_USER = 'user'
ROLE_GENIE = 'python'

USER_ANSWERS = 'USER_ANSWERS'

TRUE_OR_FALSE = 'true or false'

MAX_RETRIES = 5
MAX_VOTING_FACTOR = 1
CONTINUE_VOTE_QUORUM = 0.6
CONTINUE = 'CONTINUE'
FREE_TEXT = '_FREE'
